db:
  connTimeoutSeconds: 5
  connLatencyMilliseconds: 50
  host: "127.0.0.1"
  logConnStatus: false
  name: "vhosting2"
  port: "5432"
  sslMode: "disable"
  username: "postgres"

server:
  debugMode: true
  maxHeaderBytes: 1048576 # 1 megabyte
  port: "8001"
  readTimeoutSeconds: 15
  writeTimeoutSeconds: 15

session:
  ttlHours: 168 # 1 week
