db:
  connectionLatencyMilliseconds: 50
  connectionShowStatus: false
  connectionTimeoutSeconds: 5
  driver: "postgres"
  host: "127.0.0.1"
  name: "vhosting2"
  port: 5432
  sslEnable: false
  username: "postgres"

dbo:
  connectionLatencyMilliseconds: 500
  connectionShowStatus: false
  connectionTimeoutSeconds: 5
  driver: "postgres"
  host: "192.168.0.32"
  name: "l3"
  port: 5432
  sslEnable: false
  username: "sysadmin"

pagination:
  getLimitDefault: 100

server:
  debugEnable: false
  maxHeaderBytes: 1048576 # 1 megabyte
  port: 8001
  readTimeoutSeconds: 15
  writeTimeoutSeconds: 15

session:
  ttlHours: 168 # 7 days

stream:
  iceServers: [
    "stun:stun.l.google.com:19302"
  ]
  snapshotPeriodSeconds: 60
  snapshotShowStatus: false
  snapshotsEnable: false
