pagination:
  getLimitDefault: 100

server:
  debugEnable: false
  maxHeaderBytes: 1048576 # 1 megabyte
  port: 8000

session:
  ttlHours: 168 # 7 days

stream:
  iceServers: [
    "stun:stun.l.google.com:19302"
  ]
  snapshotPeriodSeconds: 60
  snapshotShowStatus: false
  snapshotsEnable: true
